### ISSUE TITLE
fmt fails to build with 4.14.0+trunk

### ISSUE THREAD

**Issue by shubhamkumar13** [dbuenzli/fmt#49]
I get the following error log when I try to build `fmt` with `4.14.0+trunk` and `dune.2.9.0`
```
#=== ERROR while compiling fmt.0.8.9 ==========================================#
# context     2.0.8 | linux/x86_64 | ocaml-variants.4.14.0+trunk | https://opam.ocaml.org#1fc79772
# path        ~/.opam/4.14.0+trunk/.opam-switch/build/fmt.0.8.9
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --dev-pkg false --with-base-unix true --with-cmdliner false
# exit-code   1
# env-file    ~/.opam/log/fmt-2323173-d2c37b.env
# output-file ~/.opam/log/fmt-2323173-d2c37b.out
### output ###
# [...]
# 7 | let () = ignore (Toploop.use_file Format.err_formatter "fmt_tty_top_init.ml")
#                      ^^^^^^^^^^^^^^^^
# Error: Unbound value Toploop.use_file
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/fmt.a' 'src/fmt.cmxs' 'src/fmt.cmxa' 'src/fmt.cma'
#      'src/fmt.cmx' 'src/fmt.cmi' 'src/fmt.mli' 'src/fmt_tty.a'
#      'src/fmt_tty.cmxs' 'src/fmt_tty.cmxa' 'src/fmt_tty.cma'
#      'src/fmt_tty.cmx' 'src/fmt_tty.cmi' 'src/fmt_tty.mli' 'src/fmt_top.a'
#      'src/fmt_top.cmxs' 'src/fmt_top.cmxa' 'src/fmt_top.cma'
#      'src/fmt_top.cmx' 'src/fmt_tty_top_init.ml']: exited with 10

```

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/ocaml/issues/10556
